import MainContextProvider from "@/context/MainContext";
import "./globals.css";
import SWRProvider from "@/swr/SWRProvider";
/* TOASTIFY */
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Royals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <SWRProvider>
        <MainContextProvider>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        </MainContextProvider>
      </SWRProvider>


      </body>
    </html>
  );
}
